package main

type Button struct {
	state    int
	upName   string
	downName string
	x        float64
	y        float64
}

var btns = map[string]Button{
	"start": {
		state:    0,
		upName:   "START_UP",
		downName: "START_DOWN",
		x:        36,
		y:        86,
	},
	"pause": {
		state:    0,
		upName:   "PAUSE_UP",
		downName: "PAUSE_DOWN",
		x:        85,
		y:        86,
	},
	"reset": {
		state:    0,
		upName:   "RESET_UP",
		downName: "RESET_DOWN",
		x:        136,
		y:        86,
	},
	"cps_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        85,
	},
	"cps_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        85,
	},
	"tempo_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        105,
	},
	"tempo_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        105,
	},
	"mutation_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        125,
	},
	"mutation_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        125,
	},
	"herbs_starting_nr_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        165,
	},
	"herbs_starting_nr_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        165,
	},
	"herbs_energy_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        185,
	},
	"herbs_energy_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        185,
	},
	"herbs_per_spawn_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        205,
	},
	"herbs_per_spawn_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        205,
	},
	"herbs_spawn_rate_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        225,
	},
	"herbs_spawn_rate_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        225,
	},
	"herbivores_starting_nr_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        265,
	},
	"herbivores_starting_nr_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        265,
	},
	"herbivores_spawn_energy_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        285,
	},
	"herbivores_spawn_energy_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        285,
	},
	"herbivores_breed_level_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        305,
	},
	"herbivores_breed_level_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        305,
	},
	"herbivores_move_cost_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        325,
	},
	"herbivores_move_cost_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        325,
	},
	"carnivores_starting_nr_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        365,
	},
	"carnivores_starting_nr_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        365,
	},
	"carnivores_spawn_energy_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        385,
	},
	"carnivores_spawn_energy_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        385,
	},
	"carnivores_breed_level_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        405,
	},
	"carnivores_breed_level_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        405,
	},
	"carnivores_move_cost_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        425,
	},
	"carnivores_move_cost_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        425,
	},
	"carnivores_kill_energy_plus": {
		state:    0,
		upName:   "PLUS_UP",
		downName: "PLUS_DOWN",
		x:        826,
		y:        445,
	},
	"carnivores_kill_energy_minus": {
		state:    0,
		upName:   "MINUS_UP",
		downName: "MINUS_DOWN",
		x:        811,
		y:        445,
	},
}
